### ISSUE TITLE
提交，当提交信息过多时 获取不到，截取也没用

### ISSUE THREAD

**Issue by k983551019** [DreamPWJ/jenkins-shared-library#15]
时隔几个月我又来问问题了
![image](https://github.com/DreamPWJ/jenkins-shared-library/assets/48147837/15ccb0b1-6cc9-4f52-8924-48d1693ee023)
内容如下
`fix: 【[测试不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管不用管管-客户列表-客户作废](https://www.tapd.cn/1236789/prong/tasks/view/1160863849001007580)】4`
![image](https://github.com/DreamPWJ/jenkins-shared-library/assets/48147837/e2c2f9e4-46b5-4f9a-a7ee-54adaad60940)
消息打印后只有 ` combinationMsg:> fix: ([f4cc3a4b1a](http://192.168.10.10:3000/Front/ssssss) `

**Comment by k983551019** [comment]
fix: 后的东西都没了

**Comment by DreamPWJ** [comment]
![image](https://github.com/DreamPWJ/jenkins-shared-library/assets/16730031/6f503311-321b-4ac3-984b-7debdd8e6b30)
Jenkinsti提供变更日志的方法有缺陷， 请使用我新提供的变更日志获取方法， 基于git命令 更灵活  @k983551019

**Comment by k983551019** [comment]
![image](https://github.com/DreamPWJ/jenkins-shared-library/assets/48147837/efe3252b-2630-4f56-902c-e3819af54d18)
还是解决不了，使用[XXXXXXXXXXXXXX](BBBBBBBBBBBBBBBBBBBBBBB)  不到100字符 获取不到

**Comment by DreamPWJ** [comment]
你用的這個不是我提供的新方法啊

**Comment by k983551019** [comment]
> 你用的這個不是我提供的新方法啊

ChangeLog 的genChangeLog
